import mysql.connector
from mysql.connector import Error

class CinemaDB:
    def __init__(self):
        self.config = {
            'host': 'localhost',
            'user': 'snackly',
            'password': 'get-food', 
            'database': 'cinema_snack_system'
        }

    def get_connection(self):
        return mysql.connector.connect(**self.config)

    # --- Authentication ---
    def login(self, username, password):
        conn = self.get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM users WHERE username = %s AND password = %s", (username, password))
        user = cursor.fetchone()
        cursor.close()
        conn.close()
        return user
    
    def register(self, username, password, role='customer'):
        conn = self.get_connection()
        cursor = conn.cursor()
        try:
            query = "INSERT INTO users (username, password, role) VALUES (%s, %s, %s)"
            cursor.execute(query, (username, password, role))
            conn.commit()
            return True, "User created successfully"
        except mysql.connector.Error as err:
            if err.errno == 1062: # Duplicate entry error code
                return False, "Username already exists"
            return False, str(err)
        finally:
            cursor.close()
            conn.close()

    # --- Snack Management ---
    def get_snacks(self):
        conn = self.get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM snacks WHERE is_available = TRUE")
        res = cursor.fetchall()
        cursor.close()
        conn.close()
        return res

    def update_inventory(self, snack_id, new_price, new_stock):
        conn = self.get_connection()
        cursor = conn.cursor()
        # This update will automatically fire the 'low_stock_warning' TRIGGER in MySQL
        cursor.execute("UPDATE snacks SET price = %s, stock_quantity = %s WHERE snack_id = %s", 
                       (new_price, new_stock, snack_id))
        conn.commit()
        cursor.close()
        conn.close()

    # --- Module 5: Calling the Stored Procedure ---
    def place_order(self, user_id, hall, seat, cart):
        conn = self.get_connection()
        cursor = conn.cursor()
        try:
            # Step 1: Create the Order Header once
            # We use an OUT parameter to get the new ID back from MySQL
            cursor.callproc('CreateOrderHeader', (user_id, int(hall), seat, 0))
            
            # This is a bit funky in mysql-connector, we have to fetch the OUT param
            for result in cursor.stored_results():
                pass # clear buffers
            
            # Get the ID of the order we just created
            cursor.execute("SELECT LAST_INSERT_ID()")
            order_id = cursor.fetchone()[0]

            # Step 2: Add all items from the cart to that SAME order_id
            for item in cart:
                cursor.callproc('AddItemToOrder', (order_id, item['id'], item['qty']))
            
            conn.commit()
            return True, f"Order #{order_id} placed successfully!"
        except Error as e:
            conn.rollback()
            return False, str(e)
        finally:
            cursor.close()
            conn.close()
            
    # --- Trigger Visualization (Module 5) ---
    def get_inventory_alerts(self):
        """Fetches the messages generated by the 'low_stock_warning' Trigger."""
        conn = self.get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute("SELECT * FROM inventory_logs ORDER BY tstamp DESC LIMIT 10")
        res = cursor.fetchall()
        cursor.close()
        conn.close()
        return res

    # --- Admin Order Views ---
    def get_all_orders(self):
        conn = self.get_connection()
        cursor = conn.cursor(dictionary=True)
        cursor.execute("""SELECT o.*, u.username FROM orders o 
                          JOIN users u ON o.user_id = u.user_id 
                          ORDER BY o.created_at DESC""")
        res = cursor.fetchall()
        cursor.close()
        conn.close()
        return res

    def update_status(self, order_id, status):
        conn = self.get_connection()
        cursor = conn.cursor()
        cursor.execute("UPDATE orders SET order_status = %s WHERE order_id = %s", (status, order_id))
        conn.commit()
        cursor.close()
        conn.close()

    def get_order_details(self, order_id):
        conn = self.get_connection()
        cursor = conn.cursor(dictionary=True)
        query = """
            SELECT s.name, oi.quantity, oi.price_at_time, (oi.quantity * oi.price_at_time) as subtotal
            FROM order_items oi
            JOIN snacks s ON oi.snack_id = s.snack_id
            WHERE oi.order_id = %s
        """
        cursor.execute(query, (order_id,))
        items = cursor.fetchall()
        cursor.close()
        conn.close()
        return items

    def get_user_order_history(self, user_id):
        conn = self.get_connection()
        cursor = conn.cursor(dictionary=True)
        query = "SELECT * FROM orders WHERE user_id = %s ORDER BY created_at DESC"
        cursor.execute(query, (user_id,))
        history = cursor.fetchall()
        cursor.close()
        conn.close()
        return history